repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: fix-encoding-pragma
  # - repo: https://github.com/pycqa/bandit
  #   rev: 1.7.0
  #   hooks:
  #     - id: bandit
  #       # Bandit does not need to run on test code
  #       exclude: tests/*
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
      - id: black-jupyter
  # Execute isort on all changed files (make sure the version is the same as in pyproject)
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  # Execute flake8 on all changed files (make sure the version is the same as in pyproject)
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          ["flake8-docstrings", "flake8-bugbear", "pep8-naming"]
  # - repo: https://github.com/psf/black
  #   rev: "22.1.0"
  #   hooks:
  #     - id: black-jupyter
